#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.sg.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: #@ data.values.sg.name + "-service"
  namespace: #@ data.values.sg.namespace
spec:
  selector:
    app: #@ data.values.sg.name
  ports:
    - protocol: TCP
      port: #@ data.values.sg.hostPort
      targetPort: #@ data.values.sg.containerPort
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: #@ data.values.sg.name + "-configmap"
  namespace: #@ data.values.sg.namespace
data:
  PORT: #@ data.values.sg.str.containerPort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ data.values.sg.name + "-deployment"
  namespace: #@ data.values.sg.namespace
  labels:
    app: #@ data.values.sg.name
spec:
  replicas: #@ data.values.sg.replicas
  selector:
    matchLabels:
      app: #@ data.values.sg.name
  template:
    metadata:
      labels:
        app: #@ data.values.sg.name
    spec:
      containers:
      - name: #@ data.values.sg.name
        image: #@ data.values.sg.dockerImage
        imagePullPolicy: #@ data.values.sg.imagePullPolicy
        envFrom:
        - configMapRef:
            name: #@ data.values.sg.name + "-configmap"
        ports:
        - containerPort: #@ data.values.sg.containerPort
